// Generated by grafana-k6 on 2026-08-24T01:42:40.582Z
import http from 'k6/http';
import { check, sleep } from 'k6';
import execution from 'k6/execution';
import { Rate, Trend } from 'k6/metrics';

import {
  buildScenarios,
  endpoints,
  buildThresholds,
  metricName,
  profileIdsFor,
} from '../config/performance.config.js';
import {
  authHeaders,
  login,
  normalizeUrl,
  requestTags,
  requireEnvironment,
} from '../../templates/endpoint.template.js';
import { evaluateSummary, renderConsole, renderHtml, renderMarkdown } from '../lib/report.js';

const PROFILE = __ENV.PROFILE || 'smoke';
const BASE_URL = normalizeUrl(__ENV.BASE_URL);
const SUPABASE_URL = normalizeUrl(__ENV.SUPABASE_URL || '');
const REQUEST_TIMEOUT = __ENV.REQUEST_TIMEOUT || '10s';
const SETUP_REQUEST_TIMEOUT = __ENV.SETUP_REQUEST_TIMEOUT || '60s';
const SETUP_MAX_ATTEMPTS = Math.max(1, Number(__ENV.SETUP_MAX_ATTEMPTS || '3'));
const SETUP_RETRY_DELAY_SECONDS = Math.max(0, Number(__ENV.SETUP_RETRY_DELAY_SECONDS || '2'));
const THINK_TIME_SECONDS = Number(__ENV.THINK_TIME_SECONDS || '1');
const RUN_ID = __ENV.RUN_ID || new Date().toISOString().replace(/[:.]/g, '-');
const PROFILE_IDS = profileIdsFor(PROFILE);

function buildMetrics() {
  const result = {};
  for (const profileId of PROFILE_IDS) {
    result[profileId] = {
      duration: new Trend(metricName(profileId, 'duration_ms'), true),
      success: new Rate(metricName(profileId, 'success_rate')),
      errors: new Rate(metricName(profileId, 'error_rate')),
      timeouts: new Rate(metricName(profileId, 'timeout_rate')),
      endpoints: {},
    };
    for (const endpoint of endpoints) {
      result[profileId].endpoints[endpoint.key] = {
        duration: new Trend(metricName(profileId, 'duration_ms', endpoint.key), true),
        success: new Rate(metricName(profileId, 'success_rate', endpoint.key)),
        errors: new Rate(metricName(profileId, 'error_rate', endpoint.key)),
        timeouts: new Rate(metricName(profileId, 'timeout_rate', endpoint.key)),
      };
    }
  }
  return result;
}

const metrics = buildMetrics();

export const options = {
  scenarios: buildScenarios(PROFILE),
  thresholds: buildThresholds(PROFILE_IDS, endpoints),
  setupTimeout: '4m',
  discardResponseBodies: true,
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'count'],
  userAgent: 'Fletway-k6-performance/1.0',
};

function validateRole(role, path, token) {
  const response = http.get(`${BASE_URL}${path}`, {
    headers: authHeaders(token),
    tags: requestTags({ endpointId: 'role_validation', profile: 'setup', stage: 'validate', role }),
    timeout: SETUP_REQUEST_TIMEOUT,
  });
  if (response.status !== 200) {
    throw new Error(`La validación del rol ${role} falló en ${path}. HTTP ${response.status}.`);
  }
}

export function setup() {
  requireEnvironment();
  let health;
  for (let attempt = 1; attempt <= SETUP_MAX_ATTEMPTS; attempt += 1) {
    health = http.get(`${BASE_URL}/`, {
      tags: requestTags({ endpointId: 'health', profile: 'setup', stage: 'validate', role: 'public' }),
      timeout: SETUP_REQUEST_TIMEOUT,
    });
    if (health.status === 200) break;
    const detail = health.error ? ` (${health.error})` : '';
    console.warn(`Prevalidación ${attempt}/${SETUP_MAX_ATTEMPTS}: HTTP ${health.status}${detail}.`);
    if (attempt < SETUP_MAX_ATTEMPTS) sleep(SETUP_RETRY_DELAY_SECONDS);
  }
  if (!health || health.status !== 200) {
    const detail = health?.error ? ` (${health.error})` : '';
    throw new Error(
      `El backend no superó la prevalidación tras ${SETUP_MAX_ATTEMPTS} intentos. ` +
      `HTTP ${health?.status || 0}${detail}. La prueba de rendimiento no llegó a ejecutarse.`,
    );
  }

  const clientToken = login('client', __ENV.CLIENT_EMAIL, __ENV.CLIENT_PASSWORD, {
    supabaseUrl: SUPABASE_URL,
    anonKey: __ENV.SUPABASE_ANON_KEY,
    timeout: SETUP_REQUEST_TIMEOUT,
  });
  const driverToken = login('driver', __ENV.DRIVER_EMAIL, __ENV.DRIVER_PASSWORD, {
    supabaseUrl: SUPABASE_URL,
    anonKey: __ENV.SUPABASE_ANON_KEY,
    timeout: SETUP_REQUEST_TIMEOUT,
  });
  validateRole('client', '/api/solicitudes/mis-pedidos', clientToken);
  validateRole('driver', '/api/transportista/dashboard', driverToken);
  return { clientToken, driverToken };
}

function endpointForIteration(iteration) {
  // 37 es coprimo con 100: dispersa las primeras iteraciones por toda la
  // distribución ponderada y evita que un smoke corto pruebe solo el inicio.
  const bucket = (iteration * 37) % 100;
  let upperBound = 0;
  for (const endpoint of endpoints) {
    upperBound += endpoint.weight;
    if (bucket < upperBound) return endpoint;
  }
  return endpoints[endpoints.length - 1];
}

function requestUrl(endpoint) {
  if (endpoint.key === 'buscar_localidades') {
    return `${BASE_URL}${endpoint.path}?q=${encodeURIComponent(__ENV.SEARCH_QUERY || 'Cordoba')}`;
  }
  return `${BASE_URL}${endpoint.path}`;
}

function tokenFor(endpoint, data) {
  if (endpoint.role === 'client') return data.clientToken;
  if (endpoint.role === 'driver') return data.driverToken;
  return null;
}

export function runFlow(data) {
  const profileId = execution.scenario.name;
  const endpoint = endpointForIteration(execution.scenario.iterationInTest);
  const token = tokenFor(endpoint, data);
  const tags = requestTags({ endpointId: endpoint.key, profile: profileId, stage: 'measure', role: endpoint.role });
  const response = http.get(requestUrl(endpoint), {
    headers: token ? authHeaders(token) : { Accept: 'application/json' },
    tags,
    timeout: REQUEST_TIMEOUT,
  });

  const successful = response.status === 200;
  const timedOut = String(response.error || '').toLowerCase().includes('timeout');
  check(response, { [`${endpoint.key} responde HTTP 200`]: () => successful }, tags);

  const profileMetrics = metrics[profileId];
  const endpointMetrics = profileMetrics.endpoints[endpoint.key];
  profileMetrics.duration.add(response.timings.duration);
  profileMetrics.success.add(successful);
  profileMetrics.errors.add(!successful);
  profileMetrics.timeouts.add(timedOut);
  endpointMetrics.duration.add(response.timings.duration);
  endpointMetrics.success.add(successful);
  endpointMetrics.errors.add(!successful);
  endpointMetrics.timeouts.add(timedOut);

  sleep(THINK_TIME_SECONDS);
}

export function handleSummary(data) {
  const evaluation = evaluateSummary(data, PROFILE, { runId: RUN_ID, baseUrl: BASE_URL });
  const baseName = `${RUN_ID}-${PROFILE}`;
  const paths = {
    json: `performance/results/${baseName}-summary.json`,
    markdown: `performance/reports/${baseName}-report.md`,
    html: `performance/reports/${baseName}-report.html`,
  };
  return {
    [paths.json]: JSON.stringify({ evaluation, k6: data }, null, 2),
    [paths.markdown]: renderMarkdown(evaluation),
    [paths.html]: renderHtml(evaluation),
    stdout: renderConsole(evaluation, paths),
  };
}
