import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import test from 'node:test';

const directory = path.dirname(fileURLToPath(import.meta.url));
const localPerformanceDirectory = path.resolve(directory, '../..');
const siblingPerformanceDirectory = path.resolve(localPerformanceDirectory, '../../fletway-flask-performance/performance');
const manifestPath = process.env.PERFORMANCE_MANIFEST_PATH || (fs.existsSync(path.join(localPerformanceDirectory, 'config/endpoints.manifest.json'))
  ? path.join(localPerformanceDirectory, 'config/endpoints.manifest.json')
  : path.join(siblingPerformanceDirectory, 'config/endpoints.manifest.json'));
const generatorPath = fs.existsSync(path.join(localPerformanceDirectory, 'scripts/generate-endpoint-test.mjs'))
  ? path.join(localPerformanceDirectory, 'scripts/generate-endpoint-test.mjs')
  : path.join(siblingPerformanceDirectory, 'scripts/generate-endpoint-test.mjs');
const generatorUsesSiblingFoundation = generatorPath.startsWith(siblingPerformanceDirectory);
const { renderEndpointTest } = await import(pathToFileURL(generatorPath).href);

function loadManifest() {
  assert.equal(fs.existsSync(manifestPath), true, `missing canonical manifest: ${manifestPath}`);
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

function ownedEndpoints(manifest) {
  return manifest.endpoints.filter((endpoint) => (
    ['app.py', 'routes/localidad_routes.py'].includes(endpoint.module)
    && endpoint.priority === 'P0'
  ));
}

test('Localidades/Health files match the canonical P0 manifest in both directions', () => {
  const endpoints = ownedEndpoints(loadManifest());
  const manifestIds = endpoints.map(({ id }) => id).sort();
  const diskIds = fs.readdirSync(directory)
    .filter((name) => name.endsWith('.js'))
    .map((name) => path.basename(name, '.js'))
    .sort();

  assert.deepEqual(manifestIds, ['buscar-localidades', 'health', 'localidades']);
  assert.deepEqual(diskIds, manifestIds, 'on-disk scripts must exactly match module-owned P0 endpoints');

  for (const endpoint of endpoints) {
    const filePath = path.join(directory, `${endpoint.id}.js`);
    const generatorOutputPath = generatorUsesSiblingFoundation
      ? path.join(siblingPerformanceDirectory, 'endpoints', 'localidades', `${endpoint.id}.js`)
      : filePath;
    assert.equal(fs.existsSync(filePath), true, `missing endpoint script: ${endpoint.id}`);
    assert.equal(
      fs.readFileSync(filePath).equals(Buffer.from(renderEndpointTest(endpoint, generatorOutputPath), 'utf8')),
      true,
      `generated bytes or line endings drift: ${endpoint.id}`,
    );

    const source = fs.readFileSync(filePath, 'utf8');
    const metadataMatch = source.match(/const endpoint = (\{[\s\S]*?\});\r?\n(?:\/\/.*\r?\n)*const adapter = adapterFor\(endpoint\);/);
    assert.ok(metadataMatch, `missing generated endpoint metadata: ${endpoint.id}`);
    assert.deepEqual(JSON.parse(metadataMatch[1]), {
      id: endpoint.id,
      role: endpoint.role,
      mutation: endpoint.mutation,
    }, `generated metadata drift: ${endpoint.id}`);
    assert.match(source, /adapterFor\(endpoint\)/);
    assert.match(source, /resolvePath\(adapter\.path\)/);
    assert.match(source, /http\.request\(adapter\.method/);
    assert.match(source, /export default function/);
    assert.match(source, /new Trend\(metricName/);
    assert.match(source, /new Rate\(metricName/);
    assert.match(source, /requestTags\(/);
    assert.doesNotMatch(source, /(password|jwt|Bearer\s+[A-Za-z0-9._-]{20,})\s*[:=]/i);
  }
});
