import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { renderEndpointTest } from '../../scripts/generate-endpoint-test.mjs';

const directory = path.dirname(fileURLToPath(import.meta.url));
const localManifestPath = path.resolve(directory, '../../config/endpoints.manifest.json');
const siblingManifestPath = path.resolve(directory, '../../../../fletway-flask-performance/performance/config/endpoints.manifest.json');
const manifestPath = process.env.PERFORMANCE_MANIFEST_PATH || (fs.existsSync(localManifestPath) ? localManifestPath : siblingManifestPath);

function loadManifest() {
  assert.equal(fs.existsSync(manifestPath), true, `missing canonical manifest: ${manifestPath}`);
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

test('contains every Presupuestos P0 endpoint declared in the canonical manifest', () => {
  const manifest = loadManifest();
  const endpoints = manifest.endpoints.filter((endpoint) => endpoint.module === 'routes/presupuesto_routes.py' && endpoint.priority === 'P0');
  const manifestIds = endpoints.map((endpoint) => endpoint.id).sort();
  const diskIds = fs.readdirSync(directory)
    .filter((name) => name.endsWith('.js'))
    .map((name) => path.basename(name, '.js'))
    .sort();
  assert.deepEqual(diskIds, manifestIds, 'on-disk endpoint scripts must exactly match manifest-owned Presupuestos P0 endpoints');

  for (const endpoint of endpoints) {
    const filePath = path.join(directory, `${endpoint.id}.js`);
    assert.equal(fs.existsSync(filePath), true, `missing endpoint script: ${endpoint.id}`);
    const actualBytes = fs.readFileSync(filePath);
    const generatedBytes = Buffer.from(renderEndpointTest(endpoint, filePath), 'utf8');
    assert.equal(actualBytes.equals(generatedBytes), true, `generated bytes or line endings drift: ${endpoint.id}`);
    const source = fs.readFileSync(filePath, 'utf8');
    const metadataMatch = source.match(/const endpoint = (\{[\s\S]*?\});\r?\n(?:\/\/.*\r?\n)*const adapter = adapterFor\(endpoint\);/);
    assert.ok(metadataMatch, `missing generated endpoint metadata: ${endpoint.id}`);
    assert.deepEqual(JSON.parse(metadataMatch[1]), {
      id: endpoint.id,
      role: endpoint.role,
      mutation: endpoint.mutation,
    }, `generated metadata drift: ${endpoint.id}`);
    assert.match(source, /adapterFor\(endpoint\)/);
    assert.match(source, /resolvePath\(adapter\.path\)/);
    assert.match(source, /http\.request\(adapter\.method/);
    assert.match(source, /export default function/);
    assert.match(source, /new Trend\(metricName/);
    assert.match(source, /new Rate\(metricName/);
    assert.match(source, /requestTags\(/);
    assert.doesNotMatch(source, /(password|jwt|Bearer\s+[A-Za-z0-9._-]{20,})\s*[:=]/i);
  }
});
